namespace FoodDrinkApp.Services;

public static class MockApiConfig
{
    // Replace this with the Resource endpoint generated by mockapi.io.
    // Example: https://682xxxx.mockapi.io/api/v1/foods
    public const string EndpointUrl = "https://6a1923e7489e471575197c17.mockapi.io/foods";

    public static bool IsConfigured => !string.IsNullOrWhiteSpace(EndpointUrl);
}
